### PR TITLE
Fix homepage in iPhone 6+ landscape and smaller desktop resolutions

### PR DESCRIPTION
**Pull request by ak2344**
More info in Asana.

### CODE REVIEW

**Comment by ak2344** [comment]
(This is a WIP, please don't review yet.)

**Comment by bbraithwaite** [comment]
@ak2344 To double check, this is no longer WIP right?

**Comment by ak2344** [comment]
My apologies for not updating this. Yes, this is ready.

**Comment by bbraithwaite** [comment]
This was picked up along with https://github.com/duckduckgo/duckduckgo-styles/pull/33

**Pull request closed without merging**
